<div class="supersale">
    <div class="supersale__image">

    </div>
    <div class="supersale__details">
        <div class="supersale__title">

        </div>
        <div class="timer">

        </div>
        <div class="supersale__details--bottom">
            <div class="supersale__price">
                <div class="supersale__price--final"></div>
                <div class="supersale__price--regular"></div>
            </div>
            <a href="#" class="btn btn-primary"></a>
        </div>
    </div>
</div>