<?php
/** @var $block Tickles\Supersales\Block\Sales */
/** @var Magento\Catalog\Model\Product $_saleProduct */
$_saleProduct = $block->getActiveSalesProducts()[0];
$_salePrice = $_saleProduct->getFinalPrice();
$_originalPrice = $_saleProduct->getPrice();
?>

<div class="supersale">
    <div class="supersale__image">

    </div>
    <div class="supersale__details">
        <div class="supersale__title">
            <?= $_saleProduct->getName(); ?>
        </div>
        <div class="timer">

        </div>
        <div class="supersale__details--bottom">
            <div class="supersale__price">
                <div class="supersale__price--final"><?= $block->getFormattedPrice($_salePrice); ?></div>
                <div class="supersale__price--regular"><?= $block->getFormattedPrice($_originalPrice); ?></div>
            </div>
            <a href="#" class="btn btn-primary"></a>
        </div>
    </div>
</div>